spring.application.name=agent

twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=+1${TWILIO_PHONE NO.}

deepgram.api-key=${DEEPGRAM_API_KEY}
openai.api-key=${OPENAI_API_KEY}
server.port=**********
server.ngrok-url=https://${NGROK_URL}